# Generated by Django 2.1.2 on 2018-11-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('posted_at', models.DateTimeField(verbose_name='date published')),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
