# Generated by Django 2.1.2 on 2018-11-30 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(default='Today is a great day of my life')),
                ('date', models.DateTimeField(verbose_name=datetime.datetime.now)),
            ],
        ),
    ]
